# v7
name: Deploy Nextcloud

on:
  push:
    branches:
      - asephia  # 當推送到 asephia 分支時觸發

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 環境

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 檢出代碼

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 設定 Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 從 Secrets 獲取 Docker Hub 用戶名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 從 Secrets 獲取 Docker Hub 密碼

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest .  # 構建 Docker 映像

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest  # 推送 Docker 映像到 Docker Hub

  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 環境

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 檢出代碼

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REMOTE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            echo "Successfully connected to remote server"

            # 設定環境變數
            export DB_ROOT_PASSWORD="${{ secrets.DB_ROOT_PASSWORD }}"
            export DB_DATABASE="${{ secrets.DB_DATABASE }}"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

            # 進入部署目錄
            cd /home/nextcloud-admin/asephia-nextcloud

            # 拉取最新的 Docker 映像
            docker pull ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest

            # 獲取目前運行的 nextcloud 容器的映像 ID
            CURRENT_IMAGE_ID=$(docker inspect --format='{{.Image}}' nextcloud || echo "")

            # 獲取最新的 nextcloud 映像 ID
            LATEST_IMAGE_ID=$(docker images -q ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest)

            # 只有當映像更新時才重啟容器
            if [ "$CURRENT_IMAGE_ID" != "$LATEST_IMAGE_ID" ]; then
              echo "Nextcloud image updated, restarting container..."
              docker-compose -f /home/nextcloud-admin/asephia-nextcloud/docker-compose.yml up -d --no-deps --force-recreate nextcloud
            else
              echo "Nextcloud image is already up-to-date, no restart needed."
            fi
