# v1
name: Deploy Nextcloud

on:
  push:
    branches:
      - asephia  # 當推送到 asephia 分支時觸發

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 執行環境

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 檢出代碼

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # 設置 Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 從 Secrets 獲取 Docker Hub 用戶名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 從 Secrets 獲取 Docker Hub 密碼

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest .  # 構建 Docker 映像

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest  # 推送 Docker 映像到 Docker Hub

  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 執行環境

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 檢出代碼

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REMOTE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}  # 遠程伺服器的主機地址
          username: ${{ secrets.REMOTE_USER }}  # 遠程伺服器的用戶名
          key: ${{ secrets.REMOTE_SSH_KEY }}  # 遠程伺服器的 SSH 密鑰
          script: |
            echo "Successfully connected to remote server"
            # 以下是部署指令：
            export DB_ROOT_PASSWORD="${{ secrets.DB_ROOT_PASSWORD }}"
            export DB_DATABASE="${{ secrets.DB_DATABASE }}"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            
            # 拉取最新的 Docker 映像
            docker pull ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest  
            
            # 使用 docker-compose 來重啟容器，並指定環境變數
            cd /home/nextcloud-admin/asephia-nextcloud  # 切換到包含 docker-compose.yml 的目錄
            docker-compose -f docker-compose.yml up -d  # 使用 Docker Compose 重啟容器
