# v0.3
name: Deploy Nextcloud

on:
  push:
    branches:
      - asephia  # 當推送到 asephia 分支時觸發

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 環境

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 檢出代碼

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 設定 Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 從 Secrets 獲取 Docker Hub 用戶名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 從 Secrets 獲取 Docker Hub 密碼

      - name: Build and Push Docker image
        run: |          
          docker build --build-arg DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} -t ${{ secrets.DOCKER_USERNAME }}/nextcloud:latest -f Dockerfile .  # 使用 latest 標籤來構建映像
          docker push ${{ secrets.DOCKER_USERNAME }}/nextcloud:latest  # 推送到 Docker Hub 上的 latest 標籃

  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 環境

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 檢出代碼

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REMOTE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            echo "Successfully connected to remote Windows server"

            REM 確保 Docker CLI 可用 (適用於 Windows)
            set PATH=%PATH%;C:\\Program Files\\Docker\\Docker\\resources\\bin

            REM 切換到 Nextcloud Docker Compose 目錄
            cd /d C:\\Data\\Application\\asephia-nextcloud

            REM 拉取最新的 Nextcloud 映像
            echo "Pulling the latest Nextcloud image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest

            REM 取得當前運行的 Nextcloud 容器的映像 ID
            FOR /F %%F IN ('powershell -Command "(docker inspect nextcloud | ConvertFrom-Json)[0].Image"') DO (
                SET CURRENT_IMAGE_ID=%%F
            )
            echo "Current running image ID: %CURRENT_IMAGE_ID%"

            REM 取得最新的 Nextcloud 映像 ID
            FOR /F "tokens=* USEBACKQ" %%F IN (`docker images -q ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest`) DO (
                SET LATEST_IMAGE_ID=%%F
            )
            echo "Latest image ID: %LATEST_IMAGE_ID%"

            REM 若映像有更新，則重啟容器
            IF NOT "%CURRENT_IMAGE_ID%" == "%LATEST_IMAGE_ID%" (
                echo "Nextcloud image updated, restarting container..."
                docker compose up -d --no-deps --force-recreate nextcloud
            ) ELSE (
                echo "Nextcloud image is already up-to-date, no restart needed."
            )
