name: Deploy Nextcloud

on:
  push:
    branches:
      - asephia  # 當推送到 asephia 分支時觸發

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 執行環境

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 檢出代碼

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # 設置 Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 從 Secrets 獲取 Docker Hub 用戶名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 從 Secrets 獲取 Docker Hub 密碼

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest .  # 構建 Docker 映像

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest  # 推送 Docker 映像到 Docker Hub

      - name: SSH into server and pull new image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}  # 遠程伺服器的主機地址
          username: ${{ secrets.REMOTE_USER }}  # 遠程伺服器的用戶名
          key: ${{ secrets.REMOTE_SSH_KEY }}  # 遠程伺服器的 SSH 密鑰
          script: |
            # 拉取最新的 Docker 映像
            docker pull ${{ secrets.DOCKER_USERNAME }}/asephia-nextcloud:latest  
            
            # 檢查是否存在 .env 文件，並確保環境變數正確
            if [ ! -f /path/to/your/.env ]; then
              echo "Error: .env file is missing!"
              exit 1
            fi

            # 使用 docker-compose 來重啟容器，並指定 .env 文件
            docker-compose -f /path/to/your/docker-compose.yml --env-file /path/to/your/.env up -d  # 使用 Docker Compose 重啟容器
